# Generated by Django 5.2.8 on 2026-03-31 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_jobcomment_jobrecommendation'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='category',
            field=models.CharField(choices=[('technology', 'Technology'), ('finance', 'Finance'), ('education', 'Education'), ('healthcare', 'Healthcare'), ('business', 'Business'), ('engineering', 'Engineering'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AddField(
            model_name='job',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='job',
            name='level',
            field=models.CharField(choices=[('entry', 'Entry Level'), ('mid', 'Mid Level'), ('senior', 'Senior Level'), ('executive', 'Executive')], default='mid', max_length=20),
        ),
    ]
